# Load local environment variables cleanly
spring.config.import=optional:file:.env

# Name
spring.application.name=scholax

# Database Connections mapped to .env values
spring.datasource.url=jdbc:postgresql://localhost:5432/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}

# Performance Engine Settings
spring.threads.virtual.enabled=true
spring.sql.init.mode=always

server.servlet.session.cookie.http-only=true
spring.mvc.hiddenmethod.filter.enabled=true

# ? Force Spring Security to print every internal evaluation step to the terminal log
logging.level.org.springframework.security=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
logging.level.org.springframework.security.web.authentication.AnonymousAuthenticationFilter=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY_WEB_AUTHENTICATION_ANONYMOUSAUTHENTICATIONFILTER:INFO}

# Include exception messages in server response logs (useful for checking terminal output)
server.error.include-message=${SEVER_ERROR_INCLUDE_MESSAGE}

spring.thymeleaf.cache=false
spring.devtools.livereload.enabled=true

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=true