# Load local environment variables cleanly
spring.config.import=optional:file:.env

# Name
spring.application.name=scholax

# Database Connections mapped to .env values
spring.datasource.url=jdbc:postgresql://localhost:5432/${DATABASE_NAME}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}

# Performance Engine Settings
spring.threads.virtual.enabled=true
spring.sql.init.mode=always